--- 
- name: set systemd fact 
  set_fact: 
    systemd_dir: /lib/systemd/system

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False
  when: ansible_os_family == 'RedHat'

- name: install semanage on rhel hosts
  yum:
    name: policycoreutils-python
    state: present 
  when: ansible_os_family == 'RedHat'

- name: setup k3s kubectl alias
  become: no
  lineinfile:
    path: ~/.bash_aliases
    line: 'alias k="k3s kubectl"'
    regexp: '^alias k="k3s kubectl"$'
    state: present
    create: yes
    insertafter: EOF

- name: "APT - install 'docker.io'"
  apt:
    name: "docker.io"
    update_cache: yes

- name: download pause image
  command: docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1

- name: Tag
  command: docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1 k8s.gcr.io/pause:3.1
